package component:function;

interface lambda {

    record event {
        number: s64
    }

    record response {
        factors: list<s64>
    }

    handler: func(event: event) -> response;
}

world lambda-function {
    export lambda;
}
